modLoader = "javafml"
loaderVersion = "${lang_range}"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Sxilverr"
description = "Highly customizable potion effect applier & remover."
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.${id}]]
    modId = "forge"
    mandatory = true
    versionRange = "${loader_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${id}]]
    modId = "curios"
    mandatory = false
    versionRange = "*"
    ordering = "AFTER"
    side = "BOTH"
